# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

USER root

RUN echo "===> Prepare packages..."  && \
        yum makecache fast && \
        yum install -y python sudo yum-plugin-ovl bash cronie crontabs && \
        sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && \
        chmod 0644 /etc/crontab && \
        yum clean all; \
        adduser vagrant; \
        sed -i 's/Defaults[ \t]*requiretty/Defaults !requiretty/g' /etc/sudoers; \
        echo "vagrant ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vagrant
